name: Demo Workflow

on: workflow_dispatch
jobs:
  demo_greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print greet message in console
        run: make say-hello
